spring.application.name=LibraryManagement
server.port = 8000

# H2 Database connection
spring.datasource.url=jdbc:h2:mem:librarydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=guna
spring.datasource.password=1234
spring.h2.console.enabled=true

#JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

